package uptime.observability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ApiMonitorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiMonitorAllPropertiesEquals(ApiMonitor expected, ApiMonitor actual) {
        assertApiMonitorAutoGeneratedPropertiesEquals(expected, actual);
        assertApiMonitorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiMonitorAllUpdatablePropertiesEquals(ApiMonitor expected, ApiMonitor actual) {
        assertApiMonitorUpdatableFieldsEquals(expected, actual);
        assertApiMonitorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiMonitorAutoGeneratedPropertiesEquals(ApiMonitor expected, ApiMonitor actual) {
        assertThat(actual)
            .as("Verify ApiMonitor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiMonitorUpdatableFieldsEquals(ApiMonitor expected, ApiMonitor actual) {
        assertThat(actual)
            .as("Verify ApiMonitor relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getMethod()).as("check method").isEqualTo(expected.getMethod()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getHeaders()).as("check headers").isEqualTo(expected.getHeaders()))
            .satisfies(a -> assertThat(a.getBody()).as("check body").isEqualTo(expected.getBody()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertApiMonitorUpdatableRelationshipsEquals(ApiMonitor expected, ApiMonitor actual) {
        assertThat(actual)
            .as("Verify ApiMonitor relationships")
            .satisfies(a -> assertThat(a.getSchedule()).as("check schedule").isEqualTo(expected.getSchedule()));
    }
}
