package uptime.observability.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HttpMonitorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHttpMonitorAllPropertiesEquals(HttpMonitor expected, HttpMonitor actual) {
        assertHttpMonitorAutoGeneratedPropertiesEquals(expected, actual);
        assertHttpMonitorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHttpMonitorAllUpdatablePropertiesEquals(HttpMonitor expected, HttpMonitor actual) {
        assertHttpMonitorUpdatableFieldsEquals(expected, actual);
        assertHttpMonitorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHttpMonitorAutoGeneratedPropertiesEquals(HttpMonitor expected, HttpMonitor actual) {
        assertThat(actual)
            .as("Verify HttpMonitor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHttpMonitorUpdatableFieldsEquals(HttpMonitor expected, HttpMonitor actual) {
        assertThat(actual)
            .as("Verify HttpMonitor relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getMethod()).as("check method").isEqualTo(expected.getMethod()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getHeaders()).as("check headers").isEqualTo(expected.getHeaders()))
            .satisfies(a -> assertThat(a.getBody()).as("check body").isEqualTo(expected.getBody()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHttpMonitorUpdatableRelationshipsEquals(HttpMonitor expected, HttpMonitor actual) {
        assertThat(actual)
            .as("Verify HttpMonitor relationships")
            .satisfies(a -> assertThat(a.getSchedule()).as("check schedule").isEqualTo(expected.getSchedule()));
    }
}
