name: Build and Publish Uptime O App Docker Image
permissions:
  contents: read
  packages: write
  id-token: write

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: uptime-o

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase organization name
        id: lowercase
        run: |
          echo "org_lower=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Extract metadata for Uptime O App
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.org_lower }}/${{ env.IMAGE_NAME }}
          tags: |
            # latest tag for main branch
            type=raw,value=latest,enable={{is_default_branch}}
            # branch name
            type=ref,event=branch
            # version tags for release branches  
            type=ref,event=branch,prefix=v,suffix=,pattern=release-(.+)
            # short commit hash for PRs and development
            type=sha,prefix={{branch}}-,format=short
            # PR number for pull requests
            type=ref,event=pr,prefix=pr-

      - name: Build and push Uptime O App image with Jib
        run: |
          cd uptime-o
          npm run java:docker
        env:
          JIB_IMAGE: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.org_lower }}/${{ env.IMAGE_NAME }}:latest

      - name: Verify image pushed
        run: |
          echo "Image should be available at ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.org_lower }}/${{ env.IMAGE_NAME }}:latest"
