services:
  agent-va:
    image: api-agent:latest
    container_name: agent-va
    volumes:
    - ./data/agent-va:/data
    environment:
      AGENT_ID: "1"
      API_KEY: "uptimeo_k2oXaUuhtxjZopopcSSFvnsQlI4avy2dSWe1o5Z30WA"
      API_BASE_URL: "http://localhost:8080"
      QUEUE_PATH: "/data/queue"
      CONFIG_RELOAD_INTERVAL: "1m"
    restart: unless-stopped

  agent-ny:
    image: api-agent:latest
    container_name: agent-ny
    ports:
    - "9091:9090"
    volumes:
    - ./data/agent-ny:/data
    environment:
      AGENT_ID: "2"
      API_KEY: "uptimeo_k2oXaUuhtxjZopopcSSFvnsQlI4avy2dSWe1o5Z30WA"
      API_BASE_URL: "http://localhost:8080"
      HEALTH_PORT: "9090"
      QUEUE_PATH: "/data/queue"
    restart: unless-stopped

  agent-rdn:
    image: api-agent:latest
    container_name: agent-rdn
    ports:
    - "9092:9090"
    volumes:
    - ./data/agent-rdn:/data
    environment:
      AGENT_ID: "3"
      API_KEY: "uptimeo_k2oXaUuhtxjZopopcSSFvnsQlI4avy2dSWe1o5Z30WA"
      API_BASE_URL: "http://localhost:8080"
      HEALTH_PORT: "9090"
      QUEUE_PATH: "/data/queue"
    restart: unless-stopped

  agent-chi:
    image: api-agent:latest
    container_name: agent-chi
    ports:
    - "9093:9090"
    volumes:
    - ./data/agent-chi:/data
    environment:
      AGENT_ID: "4"
      API_KEY: "uptimeo_k2oXaUuhtxjZopopcSSFvnsQlI4avy2dSWe1o5Z30WA"
      API_BASE_URL: "http://localhost:8080"
      HEALTH_PORT: "9090"
      QUEUE_PATH: "/data/queue"
    restart: unless-stopped

  agent-sf:
    image: api-agent:latest
    container_name: agent-sf
    ports:
    - "9094:9090"
    volumes:
    - ./data/agent-sf:/data
    environment:
      AGENT_ID: "5"
      API_KEY: "uptimeo_k2oXaUuhtxjZopopcSSFvnsQlI4avy2dSWe1o5Z30WA"
      API_BASE_URL: "http://localhost:8080"
      HEALTH_PORT: "9090"
      QUEUE_PATH: "/data/queue"
    restart: unless-stopped

  agent-lon:
    image: api-agent:latest
    container_name: agent-lon
    ports:
    - "9095:9090"
    volumes:
    - ./data/agent-lon:/data
    environment:
      AGENT_ID: "6"
      API_KEY: "uptimeo_k2oXaUuhtxjZopopcSSFvnsQlI4avy2dSWe1o5Z30WA"
      API_BASE_URL: "http://localhost:8080"
      HEALTH_PORT: "9090"
      QUEUE_PATH: "/data/queue"
    restart: unless-stopped

  agent-dam:
    image: api-agent:latest
    container_name: agent-dam
    ports:
    - "9096:9090"
    volumes:
    - ./data/agent-dam:/data
    environment:
      AGENT_ID: "7"
      API_KEY: "uptimeo_k2oXaUuhtxjZopopcSSFvnsQlI4avy2dSWe1o5Z30WA"
      API_BASE_URL: "http://localhost:8080"
      HEALTH_PORT: "9090"
      QUEUE_PATH: "/data/queue"
    restart: unless-stopped

  agent-sto:
    image: api-agent:latest
    container_name: agent-sto
    ports:
    - "9097:9090"
    volumes:
    - ./data/agent-sto:/data
    environment:
      AGENT_ID: "8"
      API_KEY: "uptimeo_k2oXaUuhtxjZopopcSSFvnsQlI4avy2dSWe1o5Z30WA"
      API_BASE_URL: "http://localhost:8080"
      HEALTH_PORT: "9090"
      QUEUE_PATH: "/data/queue"
    restart: unless-stopped

  agent-syd:
    image: api-agent:latest
    container_name: agent-syd
    ports:
    - "9098:9090"
    volumes:
    - ./data/agent-syd:/data
    environment:
      AGENT_ID: "9"
      API_KEY: "uptimeo_k2oXaUuhtxjZopopcSSFvnsQlI4avy2dSWe1o5Z30WA"
      API_BASE_URL: "http://localhost:8080"
      HEALTH_PORT: "9090"
      QUEUE_PATH: "/data/queue"
    restart: unless-stopped
